name: Build on Windows

on:
    workflow_call:
        inputs:
            commit-sha:
                type: string
                required: true
        outputs:
            runid:
                value: ${{github.run_id}}
    workflow_dispatch:
        inputs:
            commit-sha:
                type: string
                description: Target commit
                required: true

jobs:
    x64:
        runs-on: windows-latest
        steps:

          - name: Checkout wasmtime
            uses: actions/checkout@v4
            with:
                repository: bytecodealliance/wasmtime
                path: wasmtime
                ref: ${{inputs.commit-sha}}
                submodules: recursive

          - name: Install Rust
            uses: dtolnay/rust-toolchain@v1
            with:
                toolchain: stable
                targets: x86_64-pc-windows-msvc

          - name: Build Windows x64 Debug
            shell: pwsh
            run: |
                cd wasmtime\crates\c-api
                $env:RUSTFLAGS="-Cdebuginfo=2 -Ctarget-feature=+crt-static"
                cmake -S . -B build -A x64 -DWASMTIME_ALWAYS_BUILD=ON -DBUILD_SHARED_LIBS=OFF -DWASMTIME_TARGET=x86_64-pc-windows-msvc -DCMAKE_INSTALL_PREFIX="$PWD/debug" -DCMAKE_BUILD_TYPE=Debug
                cmake --build build --config Debug --parallel -- /m
                cmake --install build --config Debug

          - name: Build Windows x64 Release
            shell: pwsh
            run: |
                cd wasmtime\crates\c-api
                $env:RUSTFLAGS="-Ctarget-feature=+crt-static"
                cmake -S . -B build -A x64 -DWASMTIME_ALWAYS_BUILD=ON -DBUILD_SHARED_LIBS=OFF -DWASMTIME_TARGET=x86_64-pc-windows-msvc -DCMAKE_INSTALL_PREFIX="$PWD/release" -DCMAKE_BUILD_TYPE=Release
                cmake --build build --config Release --parallel -- /m
                cmake --install build --config Release

          - name: Compress Product
            shell: pwsh
            run: |
                echo ${{inputs.commit-sha}} >> VERSION.txt
                7z a wasmtime_windows_x64_debug.7z .\wasmtime\crates\c-api\debug\lib\wasmtime.lib .\wasmtime\crates\c-api\debug\include VERSION.txt
                7z a wasmtime_windows_x64_release.7z .\wasmtime\crates\c-api\release\lib\wasmtime.lib .\wasmtime\crates\c-api\release\include VERSION.txt

          - name: Upload Archive
            uses: actions/upload-artifact@v4
            with:
                name: wasmtime_windows_x64
                path: |
                    *.7z
                retention-days: 7

    arm64:
        runs-on: windows-11-arm
        steps:

          - name: Checkout wasmtime
            uses: actions/checkout@v4
            with:
                repository: bytecodealliance/wasmtime
                path: wasmtime
                ref: ${{inputs.commit-sha}}
                submodules: recursive

          - name: Install Rust
            uses: dtolnay/rust-toolchain@v1
            with:
                toolchain: stable
                targets: aarch64-pc-windows-msvc

          - name: Build Windows arm64 Debug
            shell: pwsh
            run: |
                cd wasmtime\crates\c-api
                $env:RUSTFLAGS="-Cdebuginfo=2 -Ctarget-feature=+crt-static"
                cmake -S . -B build -A arm64 -DWASMTIME_ALWAYS_BUILD=ON -DBUILD_SHARED_LIBS=OFF -DWASMTIME_TARGET=aarch64-pc-windows-msvc -DCMAKE_INSTALL_PREFIX="$PWD/debug" -DCMAKE_BUILD_TYPE=Debug
                cmake --build build --config Debug --parallel -- /m
                cmake --install build --config Debug

          - name: Build Windows arm64 Release
            shell: pwsh
            run: |
                cd wasmtime\crates\c-api
                $env:RUSTFLAGS="-Ctarget-feature=+crt-static"
                cmake -S . -B build -A arm64 -DWASMTIME_ALWAYS_BUILD=ON -DBUILD_SHARED_LIBS=OFF -DWASMTIME_TARGET=aarch64-pc-windows-msvc -DCMAKE_INSTALL_PREFIX="$PWD/release" -DCMAKE_BUILD_TYPE=Release
                cmake --build build --config Release --parallel -- /m
                cmake --install build --config Release

          - name: Compress Product
            shell: pwsh
            run: |
                echo ${{inputs.commit-sha}} >> VERSION.txt
                7z a wasmtime_windows_arm64_debug.7z .\wasmtime\crates\c-api\debug\lib\wasmtime.lib .\wasmtime\crates\c-api\debug\include VERSION.txt
                7z a wasmtime_windows_arm64_release.7z .\wasmtime\crates\c-api\release\lib\wasmtime.lib .\wasmtime\crates\c-api\release\include VERSION.txt

          - name: Upload Archive
            uses: actions/upload-artifact@v4
            with:
                name: wasmtime_windows_arm64
                path: |
                    *.7z
                retention-days: 7